services:
  db:
    image: postgres:16-alpine
    container_name: node_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node_db
    ports:
      - "5432:5432"
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data:
